name: bjuraga.ExpandARM.CD
trigger: none
resources:
- repo: self
  clean: true
variables:
  Parameters.solution: '**\*.sln'
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'

jobs:
- job: CD
  pool:
    name: Hosted VS2017
    demands: 
    - msbuild
    - visualstudio
    - vstest
  steps:
  - template: templates/build-and-test.yml  # Template reference
  - template: templates/deploy.yml  # Template reference