name: bjuraga.ExpandARM.CD
trigger: none
resources:
- repo: self
  clean: true
variables:
  Parameters.solution: '**\*.sln'
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'

jobs:
- job: CI
  pool:
    name: Hosted VS2017
    demands: 
    - msbuild
    - visualstudio
    - vstest
  steps:
  - task: gittools.gitversion.gitversion-task.GitVersion@3
    displayName: GitVersion
    inputs:
      updateAssemblyInfo: true
  
  - task: NuGetToolInstaller@0
    displayName: 'Use NuGet 4.4.1'
    inputs:
      versionSpec: 4.4.1
  
  - task: NuGetCommand@2
    displayName: 'NuGet restore'
    inputs:
      restoreSolution: '$(Parameters.solution)'
  
  - task: VSBuild@1
    displayName: 'Build solution **\*.sln'
    inputs:
      solution: '$(Parameters.solution)'  
      platform: '$(BuildPlatform)'  
      configuration: '$(BuildConfiguration)'  
  
  - task: VSTest@2
    displayName: 'VsTest - testAssemblies'
    inputs:
      testAssemblyVer2: |
       **\$(BuildConfiguration)\*test*.dll
       !**\obj\**  
      codeCoverageEnabled: true  
      platform: '$(BuildPlatform)'  
      configuration: '$(BuildConfiguration)'

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: src/  
      Contents: '**/bin/$(BuildConfiguration)/**'  
      TargetFolder: '$(build.artifactstagingdirectory)'
      
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(build.artifactstagingdirectory)' 
      #includeRootFolder: true
      archiveType: 'zip' # Options: zip, 7z, tar, wim
      #tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
      archiveFile: '$(build.artifactstagingdirectory)/$(Build.BuildId).zip' 
      replaceExistingArchive: true 
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts to VSTS'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
  
  - task: marcelo-formentao.github-tools.github-release-publish-task.GitHubReleasePublish@0
    displayName: 'Publish Artifacts to GitHub'
    inputs:
      githubEndpoint: 'GitHub_Conn'  
      githubRepository: bjuraga/ExpandARM  
      githubReleaseDraft: false  
      githubReleasePrerelease: true  
      githubReleaseAsset: '$(build.artifactstagingdirectory)/**/*.zip'  
  
