name: bjuraga.ExpandARM.CI
trigger:
  branches:
    include:
    - master
    - feature/*
  paths:
    exclude:
    - README.md
resources:
- repo: self
  clean: true
variables:
  Parameters.solution: '**\*.sln'
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'

jobs:
- job: CI
  pool:
    name: Hosted VS2017
    demands: 
    - msbuild
    - visualstudio
    - vstest
  steps:
  - task: gittools.gitversion.gitversion-task.GitVersion@3
    displayName: GitVersion
    inputs:
      updateAssemblyInfo: true
  
  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: restore
      projects: '$(Parameters.solution)'
  
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: build
      projects: '$(Parameters.solution)'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet test'
    inputs:
      command: test
      projects: '**/*Tests/*.csproj'
      arguments: '--configuration $(BuildConfiguration) --collect "Code coverage"'
  
  - task: VSTest@2
    displayName: 'VsTest - testAssemblies'
    inputs:
      testAssemblyVer2: |
       **\$(BuildConfiguration)\*test*.dll
       !**\obj\**  
      codeCoverageEnabled: true  
      platform: '$(BuildPlatform)'  
      configuration: '$(BuildConfiguration)'
      
