name: bjuraga.ExpandARM.CI
trigger:
  branches:
    include:
    - master
    - feature/*
  paths:
    exclude:
    - README.md
resources:
- repo: self
  clean: true
variables:
  Parameters.solution: '**\*.sln'
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'

jobs:
- job: CI
  pool:
    name: Hosted VS2017
    demands: 
    - msbuild
    - visualstudio
    - vstest
  steps:
  - template: templates/build-and-test.yml  # Template reference

