parameters:
  Parameters.solution: 'ExpandARM.sln'
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'

steps:
- task: gittools.gitversion.gitversion-task.GitVersion@4
  displayName: GitVersion
  inputs:
    updateAssemblyInfo: true

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(Parameters.solution)'

- task: MSBuild@1
  inputs:
    solution: '$(Parameters.solution)'

- task: VSTest@2
  displayName: 'VsTest - testAssemblies'
  inputs:
    testAssemblyVer2: |
     **\$(BuildConfiguration)\*test*.dll
     !**\obj\**  
    codeCoverageEnabled: true  
    platform: '$(BuildPlatform)'  
    configuration: '$(BuildConfiguration)'
