parameters:
  Parameters.solution: 'ExpandARM.sln'
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'

steps:
- task: gittools.gitversion.gitversion-task.GitVersion@3
  displayName: GitVersion
  inputs:
    updateAssemblyInfo: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: publish
    projects: 'src/ExpandARM/ExpandARM.csproj'
    arguments: '-c Release -r win-x64 -o bin\publish --self-contained'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish locally'
  inputs:
    command: test
    projects: '**/*E2ETests/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --collect "Code coverage"'
      
