parameters:
  Parameters.solution: 'ExpandARM.sln'
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish locally'
  inputs:
    command: custom
    custom: 'publish'
    arguments: ' ./src/ExpandARM/ExpandARM.csproj -c Release -r win-x64 -o bin\publish --self-contained'
   
- task: DotNetCoreCLI@2
  displayName: 'dotnet e2e tests'
  inputs:
    command: test
    projects: '**/*E2ETests/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --collect "Code coverage"'
      
